# Created by: Dennis Herrmann <dhn@FreeBSD.org>
# $FreeBSD: head/net/p5-XML-Fast/Makefile 300897 2012-07-14 14:29:18Z beat $

PORTNAME=	XML-Fast
PORTVERSION=	0.11
CATEGORIES=	net
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dhn@FreeBSD.org
COMMENT=	Simple and very fast XML to hash conversion

PERL_CONFIGURE=	yes

MAN3=		XML::Fast.3

.include <bsd.port.mk>
