# Created by: nemysis <nemysis@gmx.ch>
# $FreeBSD$

PORTNAME=	Test-Pod-Coverage
PORTVERSION=	1.08
CATEGORIES=	net
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	nemysis@gmx.ch
COMMENT=	Check for pod coverage in your distribution

PERL_CONFIGURE=	yes

MAN3=		Test::Pod::Coverage.3

.include <bsd.port.mk>
