# Created by: Eugene Grosbein <ports@grosbein.net>
# $FreeBSD: head/devel/py-application/Makefile 300896 2012-07-14 13:54:48Z beat $

PORTNAME=	application
PORTVERSION=	1.4.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}
DIST_SUBDIR=	python

MAINTAINER=	ports@grosbein.net
COMMENT=	Basic building blocks for python applications

USE_PYTHON=	yes
USE_PYDISTUTILS=yes
PYDISTUTILS_PKGNAME=python_${PORTNAME}

.include <bsd.port.mk>
