# Created by: Rusmir Dusko <nemysis@FreeBSD.org>
# $FreeBSD$

PORTNAME=	Test-Pod-Coverage
PORTVERSION=	1.08
CATEGORIES=	net
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	nemysis@FreeBSD.org
COMMENT=	Check for pod coverage in your distribution

PERL_CONFIGURE=	yes

MAN3=		Test::Pod::Coverage.3

.include <bsd.port.mk>
